version: '3.1'

services:
  #db:
  #  image: mysql:latest
  #  restart: always
  #  volumes:
  #    - ./sql:/docker-entrypoint-initdb.d
  #  environment:
  #    MYSQL_ROOT_PASSWORD: rootpassword
  db:
    image: postgres
    restart: always
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 5001:8080

  web:
    build: .
    ports:
      - 5000:5000
    # For development, only
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - .:/app